# Generated by Django 4.0.6 on 2022-11-12 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
