# Generated by Django 4.1.2 on 2022-12-01 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_exercise_slug_exerciseinworkout_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
