# Generated by Django 4.1.2 on 2022-12-01 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_workout_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='recipe',
            name='photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='workout',
            name='photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
