# Generated by Django 4.1.2 on 2022-12-04 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='workout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.activeworkout'),
        ),
    ]
