# Generated by Django 4.1.2 on 2022-12-10 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_event_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='workout',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.activeworkout'),
        ),
    ]
