# Generated by Django 4.1.2 on 2022-12-10 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_event_workout'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipestep',
            name='number',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
    ]
