# Generated by Django 4.1.2 on 2022-12-10 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_recipestep_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipestep',
            name='photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
