# Generated by Django 4.1.2 on 2022-12-10 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_recipestep_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ings',
            field=models.TextField(null=True),
        ),
    ]
